#!/bin/bash
###############################################################################
# Git Sync Push - Cloud VM
#
# Pushes vault changes (drafts, updates, signals) to Git repository.
# Runs every 5 minutes via cron/PM2.
#
# SECRETS NEVER SYNC: .env, *_token.json, whatsapp_session/
###############################################################################

set -e

REPO_DIR="/root/AI_EMPLOYEE_APP"
cd "$REPO_DIR"

echo "[$(date -u +'%Y-%m-%d %H:%M:%S UTC')] Git Sync Push: Starting..."

# Stage all changes
echo "[$(date -u +'%Y-%m-%d %H:%M:%S UTC')] Staging changes..."
git add -A

# Check if there are changes to commit
if git diff --cached --quiet; then
    echo "[$(date -u +'%Y-%m-%d %H:%M:%S UTC')] No changes to commit."
    exit 0
fi

# Show what changed
echo "[$(date -u +'%Y-%m-%d %H:%M:%S UTC')] Changes detected:"
git status --short

# Commit with timestamp
TIMESTAMP=$(date -u +'%Y-%m-%d %H:%M:%S UTC')
git commit -m "Cloud update: $TIMESTAMP

🤖 Generated by AI Employee - Platinum Tier Cloud

Changes:
- Draft replies from AI Auto-Approver
- Watcher detections
- Cloud updates/signals
- Vault state changes

⚠️  Secrets excluded via .gitignore" || echo "[$(date -u +'%Y-%m-%d %H:%M:%S UTC')] No new commits (nothing to commit)"

# Push to remote
echo "[$(date -u +'%Y-%m-%d %H:%M:%S UTC')] Pushing to remote..."
git push origin main

echo "[$(date -u +'%Y-%m-%d %H:%M:%S UTC')] Git Sync Push: Complete ✅"
