#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Social Media Scheduler - AI Employee

Generates social media post drafts at scheduled intervals.
Creates draft posts in Pending_Approval for human review.

Usage:
    python social_media_scheduler.py --vault AI_Employee_Vault
"""

import sys
import os
import json
import random
from pathlib import Path
from datetime import datetime, timedelta

# Fix Windows encoding
if sys.stdout.encoding != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent))


class SocialMediaScheduler:
    """Generate social media post drafts"""

    def __init__(self, vault_path: str = "AI_Employee_Vault"):
        self.vault_path = Path(vault_path)
        self.pending_path = self.vault_path / "Pending_Approval"
        self.config_path = Path(__file__).parent.parent / ".claude" / "skills" / "research-linkedin-generator" / "daily_topics.json"

    def generate_linkedin_draft(self, topic: str) -> Path:
        """Generate a LinkedIn post draft"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        slug = topic.lower().replace(" ", "_")[:30]
        filename = f"LINKEDIN_POST_DRAFT_{timestamp}_{slug}.md"

        # Get recent posts for inspiration
        hashtags = "#Technology #Innovation #AI #SoftwareDevelopment #TechTrends"

        content = f"""---
type: linkedin_post
action: post_to_linkedin
platform: linkedin
created: {datetime.now().isoformat()}
expires: {(datetime.now() + timedelta(days=7)).isoformat()}
status: pending_approval
draft_type: scheduled
topic: {topic}
---

# LinkedIn Post: {topic}

## Draft Content
{self._generate_post_content(topic)}

## Hashtags
{hashtags}

## Scheduling
- Generated: {datetime.now().strftime("%Y-%m-%d %H:%M")}
- Best time to post: 9-11 AM or 2-4 PM weekdays
- Review before approving

## Notes
This is an auto-generated draft. Please:
1. Review for accuracy and tone
2. Add specific examples or personal insights
3. Adjust hashtags for relevance
4. Approve by moving to Approved/ folder

---
*Generated by Social Media Scheduler*
"""

        draft_file = self.pending_path / filename
        draft_file.parent.mkdir(parents=True, exist_ok=True)
        draft_file.write_text(content, encoding='utf-8')

        return draft_file

    def _generate_post_content(self, topic: str) -> str:
        """Generate post content based on topic"""
        # Professional templates based on topic type
        templates = {
            "ai": """🚀 Exploring the latest in AI and machine learning

The pace of innovation in artificial intelligence is accelerating rapidly. From improved code assistants to sophisticated language models, we're seeing tools that transform how we work and create.

Key developments worth watching:
• More accessible AI development tools
• Enhanced accuracy and reliability
• Better integration into existing workflows
• Focus on ethical AI implementation

What AI tools are you finding most valuable in your work?

{hashtags}""",
            "rust": """🦀 Rust continues to gain momentum in systems programming

The language's focus on memory safety without sacrificing performance makes it increasingly attractive for infrastructure projects. We're seeing wider adoption in:

• Cloud services and infrastructure
• WebAssembly applications
• Embedded systems
• Command-line tools

The growing ecosystem and improved tooling are lowering the barrier to entry.

Have you explored Rust for your projects? What was your experience?

{hashtags}""",
            "python": """🐍 Python's dominance in AI/ML shows no signs of slowing

The language's simplicity and powerful libraries make it the go-to choice for data science and machine learning. But Python's reach extends far beyond:

• Web development with Django/FastAPI
• Automation and scripting
• Microservices architecture
• Educational programming

The upcoming Python versions continue to improve performance and type hints.

What's your favorite Python use case?

{hashtags}""",
            "typescript": """💡 TypeScript has become essential for modern JavaScript development

The static typing and enhanced IDE experience have made TypeScript the default for many teams. Key benefits include:

• Catch errors at compile time
• Better code documentation
• Improved refactoring
• Enhanced team collaboration

With Node.js fully embracing TypeScript, there's never been a better time to adopt it.

How has TypeScript improved your development workflow?

{hashtags}""",
            "default": """💭 Thoughts on {topic}

The technology landscape continues to evolve rapidly. Staying current with emerging trends and best practices is essential for professional growth.

Key areas to focus on:
• Continuous learning and skill development
• Building practical projects
• Engaging with the developer community
• Sharing knowledge with others

What resources or approaches do you find most effective for staying up to date?

{hashtags}"""
        }

        # Select appropriate template
        topic_lower = topic.lower()
        if "ai" in topic_lower or "machine learning" in topic_lower or "claude" in topic_lower:
            return templates["ai"].format(hashtags="#AI #MachineLearning #Technology")
        elif "rust" in topic_lower:
            return templates["rust"].format(hashtags="#Rust #SystemsProgramming #Coding")
        elif "python" in topic_lower:
            return templates["python"].format(hashtags="#Python #Programming #Developer")
        elif "typescript" in topic_lower or "javascript" in topic_lower:
            return templates["typescript"].format(hashtags="#TypeScript #JavaScript #WebDev")
        else:
            return templates["default"].format(
                topic=topic,
                hashtags="#Technology #SoftwareDevelopment #Innovation"
            )

    def generate_twitter_draft(self, topic: str) -> Path:
        """Generate a Twitter post draft"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        slug = topic.lower().replace(" ", "_")[:30]
        filename = f"TWITTER_POST_DRAFT_{timestamp}_{slug}.md"

        # Twitter posts are shorter (max 280 chars)
        content = f"""---
type: twitter_post
action: post_to_twitter
platform: twitter
created: {datetime.now().isoformat()}
expires: {(datetime.now() + timedelta(days=2)).isoformat()}
status: pending_approval
draft_type: scheduled
topic: {topic}
---

# Twitter Post: {topic}

## Draft Content
{self._generate_twitter_content(topic)}

## Notes
Max 280 characters. Review before approving.

---
*Generated by Social Media Scheduler*
"""

        draft_file = self.pending_path / filename
        draft_file.parent.mkdir(parents=True, exist_ok=True)
        draft_file.write_text(content, encoding='utf-8')

        return draft_file

    def _generate_twitter_content(self, topic: str) -> str:
        """Generate Twitter content (shorter)"""
        templates = [
            f"Exploring {topic} - the innovation potential is incredible. What's your take on the latest developments? #Tech",
            f"Just diving into {topic}. The possibilities are exciting! Who else is exploring this space? #Technology",
            f"{topic} continues to shape our industry. Are you leveraging these tools yet? #Innovation",
            f"Quick thought: {topic} is transforming how we work. Stay curious and keep learning! #DevLife",
        ]
        return random.choice(templates)

    def run_scheduled_generation(self):
        """Run the scheduled social media generation"""
        print("=" * 60)
        print("SOCIAL MEDIA SCHEDULER")
        print("=" * 60)
        print(f"Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print()

        # Load daily topics
        if self.config_path.exists():
            with open(self.config_path) as f:
                config = json.load(f)
            topics = config.get("daily_topics", [])
        else:
            # Default topics
            topics = [
                {"topic": "AI and Software Development"},
                {"topic": "Cloud Computing Trends"},
                {"topic": "Developer Productivity"},
            ]

        if not topics:
            print("No topics configured")
            return

        # Select topic based on day/time
        day_index = datetime.now().weekday() % len(topics)
        topic_config = topics[day_index]
        topic = topic_config["topic"]

        print(f"Topic: {topic}")
        print("-" * 40)

        # Generate posts
        try:
            linkedin_draft = self.generate_linkedin_draft(topic)
            print(f"✓ LinkedIn draft: {linkedin_draft.name}")
        except Exception as e:
            print(f"✗ LinkedIn draft failed: {e}")

        try:
            twitter_draft = self.generate_twitter_draft(topic)
            print(f"✓ Twitter draft: {twitter_draft.name}")
        except Exception as e:
            print(f"✗ Twitter draft failed: {e}")

        print()
        print("=" * 60)
        print("Scheduler complete. Review drafts in Pending_Approval/")
        print("=" * 60)


def main():
    """Main entry point"""
    import argparse

    parser = argparse.ArgumentParser(
        description="Social Media Scheduler - Generate post drafts"
    )
    parser.add_argument(
        "--vault",
        default="AI_Employee_Vault",
        help="Path to Obsidian vault"
    )
    parser.add_argument(
        "--topic",
        help="Specific topic to generate (overrides schedule)"
    )
    parser.add_argument(
        "--platform",
        choices=["linkedin", "twitter", "all"],
        default="all",
        help="Platform to generate for"
    )

    args = parser.parse_args()

    scheduler = SocialMediaScheduler(args.vault)

    if args.topic:
        print(f"Generating post for: {args.topic}")
        if args.platform in ["linkedin", "all"]:
            draft = scheduler.generate_linkedin_draft(args.topic)
            print(f"Created: {draft.name}")
        if args.platform in ["twitter", "all"]:
            draft = scheduler.generate_twitter_draft(args.topic)
            print(f"Created: {draft.name}")
    else:
        scheduler.run_scheduled_generation()


if __name__ == "__main__":
    main()
