#!/usr/bin/env python3
"""
Check Overdue Invoices - Xero Manager Cron Job

This script runs weekly (Mondays at 5 PM) to check Xero for overdue invoices
and create action files for any requiring attention.

Usage:
    python check_overdue_invoices.py --vault AI_Employee_Vault
"""

import argparse
import os
import sys
from datetime import datetime, timezone
from pathlib import Path


def check_overdue_invoices(vault_path: str):
    """
    Check Xero for overdue invoices and create action files.

    Args:
        vault_path: Path to the AI Employee Vault
    """
    # Import Xero MCP tools
    try:
        from mcp_servers.xero_mcp.server import find_invoices
    except ImportError:
        print("ERROR: Xero MCP server not found. Please ensure xero-mcp is installed.")
        sys.exit(1)

    needs_action_path = Path(vault_path) / "Needs_Action"

    # Get overdue invoices (invoices due before today with status != PAID)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    try:
        # Call Xero MCP to get overdue invoices
        # This would be done through Claude Code with Xero MCP
        # For now, create a placeholder action file
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

        action_file = needs_action_path / f"XERO_INVOICE_REVIEW_{timestamp}.md"

        content = f"""---
type: xero_invoice_review
service: xero
priority: medium
status: pending
created: {datetime.now(timezone.utc).isoformat()}
---

# Weekly Xero Invoice Review

**Date:** {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}

## Overdue Invoices

Please check Xero for overdue invoices requiring follow-up:

1. **Invoices > 30 days overdue** - Contact clients for payment
2. **Invoices 7-30 days overdue** - Send payment reminders
3. **Upcoming invoices due this week** - Prepare for expected payments

## Suggested Actions

- [ ] Review overdue invoices in Xero
- [ ] Send payment reminders to clients with invoices 7-30 days overdue
- [ ] Contact clients with invoices > 30 days overdue
- [ ] Update cash flow forecast based on expected payments

## Notes

This automated check runs weekly on Mondays at 5 PM.
For detailed invoice information, use Claude Code with the Xero MCP:

```
"Show me overdue invoices from Xero"
"List invoices due in the next 7 days"
"Which clients have outstanding invoices > 30 days?"
```

---
*Generated by AI Employee - Xero Manager*
"""

        # Create action file
        action_file.write_text(content)

        print(f"✅ Created invoice review action file: {action_file.name}")
        print(f"   Location: {action_file}")
        print("\nNext steps:")
        print("1. Use Claude Code with Xero MCP to check actual overdue invoices")
        print("2. Review and execute suggested actions")
        print("3. Move to Done/ when complete")

    except Exception as e:
        print(f"ERROR: Failed to check overdue invoices: {e}")
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description="Check Xero for overdue invoices and create action files"
    )
    parser.add_argument(
        "--vault",
        required=True,
        help="Path to the AI Employee Vault"
    )

    args = parser.parse_args()

    # Validate vault path
    vault_path = Path(args.vault)
    if not vault_path.exists():
        print(f"ERROR: Vault path does not exist: {vault_path}")
        sys.exit(1)

    # Ensure Needs_Action directory exists
    needs_action_path = vault_path / "Needs_Action"
    needs_action_path.mkdir(parents=True, exist_ok=True)

    # Run the invoice check
    print("🔍 Checking Xero for overdue invoices...")
    check_overdue_invoices(args.vault)
    print("✅ Invoice review check complete!")


if __name__ == "__main__":
    main()
