#!/usr/bin/env python3
"""
Planning Agent Skill Invoker

This script allows Claude Code to invoke the planning-agent skill.

Usage:
    python invoke.py "Create a plan for client onboarding"
    python invoke.py "Break down this project into steps"

Returns:
    JSON output with status and plan details
"""

import sys
import os
import json
import argparse
from pathlib import Path
from datetime import datetime

# Add project root to path
project_root = Path(__file__).parent.parent.parent.parent
sys.path.insert(0, str(project_root))


def invoke_planning(task: str, vault_path: str = None) -> dict:
    """
    Invoke the planning agent skill.

    Args:
        task: Task or project to plan
        vault_path: Path to Obsidian vault

    Returns:
        dict: Result with status and plan details
    """
    try:
        if vault_path is None:
            vault_path = project_root / "AI_Employee_Vault"
        else:
            vault_path = Path(vault_path)  # Convert string to Path

        task_lower = task.lower()
        keywords = ["plan", "breakdown", "steps", "strategy", "roadmap", "implementation"]

        if not any(keyword in task_lower for keyword in keywords):
            return {
                "status": "error",
                "error": "Task not recognized. Use keywords like: 'plan', 'breakdown', 'steps', 'strategy'"
            }

        # Extract the objective from task
        objective = task
        for prefix in ["create a plan for", "break down", "plan for", "steps for"]:
            if objective.lower().startswith(prefix):
                objective = objective[len(prefix):].strip()
                break

        # Create plan file
        plans_folder = vault_path / "Plans"
        plans_folder.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"PLAN_{timestamp}.md"
        filepath = plans_folder / filename

        # Create structured plan
        plan_content = f"""---
type: execution_plan
status: draft
created: {datetime.now().isoformat()}
objective: {objective}
---

# Execution Plan: {objective}

**Generated by:** Planning Agent Skill (via Claude Code)
**Created:** {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Objective
{objective}

## Analysis
This plan will be executed using available AI Employee skills and capabilities.

## Implementation Strategy

### Phase 1: Planning
- [ ] Define clear success criteria
- [ ] Identify required resources
- [ ] Estimate time requirements
- [ ] Assess potential risks

### Phase 2: Execution
- [ ] Execute using appropriate skills
- [ ] Monitor progress
- [ ] Handle unexpected issues
- [ ] Document decisions

### Phase 3: Completion
- [ ] Verify all objectives met
- [ ] Document outcomes
- [ ] Move to Done/

## Required Skills
- Planning and coordination
- Domain-specific skills (as needed)
- Approval workflow for sensitive actions

## Next Steps
1. Review this plan
2. Adjust phases as needed
3. Use Ralph or manual execution to implement
4. Track progress in this file

## Notes
- Plan created via skill invocation
- Update this file as execution progresses
- Use approval workflow for external actions

---
*Planning Agent Skill - Execution Plan*
"""

        filepath.write_text(plan_content)

        print(f"[*] Execution plan created: {filename}", file=sys.stderr)

        return {
            "status": "success",
            "action": "Execution plan created",
            "file_path": str(filepath),
            "objective": objective,
            "summary": f"Plan created for: {objective}",
            "next_steps": [
                f"Review plan at: {filepath}",
                "Adjust phases as needed",
                "Execute using Ralph or manual approach"
            ],
            "error": None
        }

    except Exception as e:
        print(f"[✗] Error: {e}", file=sys.stderr)
        return {
            "status": "error",
            "error": str(e),
            "action": None
        }


def main():
    """Main entry point for skill invocation."""
    parser = argparse.ArgumentParser(
        description="Invoke planning-agent skill"
    )
    parser.add_argument(
        "task",
        help="Task or project to create a plan for"
    )
    parser.add_argument(
        "--vault",
        help="Path to Obsidian vault",
        default=None
    )

    args = parser.parse_args()

    result = invoke_planning(args.task, args.vault)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
